module.exports = {
	name: `getProgramNumber`,
	description: 'Something',

	run(number) {
		switch (number) {
			default:
				return -1;
			case (0):
				return 'grandpiano';
			case (1):
				return 'brightpiano';
			case (2):
				return 'electricpiano';
			case (3):
				return 'harpsipiano';
			case (4):
				return 'synthpiano';
			case (5):
				return 'synthpiano2';
			case (6):
				return 'harpsichord';
			case (7):
				return 'clavinet';
			case (8):
				return 'celesta';
			case (9):
				return 'glockenspiel';
			case (10):
				return 'musicbox';
			case (11):
				return 'vibraphone';
			case (12):
				return 'marimba';
			case (13):
				return 'xylophone';
			case (14):
				return 'bells';
			case (15):
				return 'dulcimer';
			case (16):
				return 'organ';
			case (17):
				return 'percussiveorgan';
			case (18):
				return 'rockorgan';
			case (19):
				return 'churchorgan';
			case (20):
				return 'reedorgan';
			case (21):
				return 'accordian';
			case (22):
				return 'harmonica';
			case (23):
				return 'tangoaccordian';
			case (24):
				return 'nylonguitar';
			case (25):
				return 'steelguitar';
			case (26):
				return 'jazzguitar';
			case (27):
				return 'cleanguitar';
			case (28):
				return 'mutedguitar';
			case (29):
				return 'electricguitar';
			case (30):
				return 'distortedguitar';
			case (31):
				return 'harmonicguitar';
			case (32):
				return 'acousticbass';
			case (33):
				return 'fingerbass';
			case (34):
				return 'pickbass';
			case (36):
				return 'slapbass1';
			case (37):
				return 'slapbass2';
			case (38):
				return 'synthbass1';
			case (39):
				return 'synthbass2';
			case (40):
				return 'violin';
			case (41):
				return 'viola';
			case (42):
				return 'cello';
			case (43):
				return 'doublebass';
			case (44):
				return 'tremolo';
			case (45):
				return 'pizzicato';
			case (46):
				return 'harp';
			case (47):
				return 'timpani';
			case (48):
				return 'strings1';
			case (49):
				return 'string2';
			case (50):
				return 'synthstrings1';
			case (51):
				return 'synthstrings2';
			case (52):
				return 'aahchoir';
			case (53):
				return 'oohchoir';
			case (54):
				return 'synthvoice';
			case (55):
				return 'orchestrahit';
			case (56):
				return 'trumpet';
			case (57):
				return 'trombone';
			case (58):
				return 'tuba';
			case (60):
				return 'frenchhorn';
			case (61):
				return 'brass';
			case (62):
				return 'synthbrass1';
			case (63):
				return 'synthbrass2';
			case (64):
				return 'sopranosax';
			case (65):
				return 'altosax';
			case (66):
				return 'tenorsax';
			case (67):
				return 'baritonesax';
			case (68):
				return 'oboe';
			case (69):
				return 'englishhorn';
			case (70):
				return 'bassoon';
			case (71):
				return 'clarinet';
			case (72):
				return 'piccolo';
			case (73):
				return 'flute';
			case (74):
				return 'recorder';
			case (75):
				return 'panflute';
			case (76):
				return 'bottle';
			case (77):
				return 'shakuhachi';
			case (78):
				return 'whistle';
			case (79):
				return 'ocarina';
			case (80):
				return 'squarelead';
			case (81):
				return 'sawlead';
			case (82):
				return 'calliopelead';
			case (83):
				return 'chifflead';
			case (84):
				return 'charanglead';
			case (85):
				return 'voicelead';
			case (86):
				return 'fifthslead';
			case (87):
				return 'basslead';
			case (88):
				return 'newpad';
			case (89):
				return 'warmpad';
			case (90):
				return 'polypad';
			case (91):
				return 'choirpad';
			case (92):
				return 'bowedpad';
			case (93):
				return 'metalpad';
			case (94):
				return 'halopad';
			case (95):
				return 'sweeppad';
			case (96):
				return 'rainfx';
			case (97):
				return 'soundtrackfx';
			case (98):
				return 'crystalfx';
			case (99):
				return 'atmospherefx';
			case (100):
				return 'brightnessfx';
			case (101):
				return 'goblinsfx';
			case (102):
				return 'echoesfx';
			case (103):
				return 'scififx';
			case (104):
				return 'sitar';
			case (105):
				return 'banjo';
			case (106):
				return 'shamisen';
			case (107):
				return 'koto';
			case (108):
				return 'kalimba';
			case (109):
				return 'bagpipe';
			case (110):
				return 'fiddle';
			case (111):
				return 'shanai';
			case (112):
				return 'twinklebell';
			case (113):
				return 'agogo';
			case (114):
				return 'steeldrums';
			case (115):
				return 'woodblock';
			case (116):
				return 'taikodrums';
			case (117):
				return 'tomtom';
			case (118):
				return 'synthdrum';
			case (119):
				return 'reversecymbal';
			case (120):
				return 'guitarfret';
			case (121):
				return 'breath';
			case (122):
				return 'seashore';
			case (123):
				return 'birdtweet';
			case (124):
				return 'ringtone';
			case (125):
				return 'helicopter';
			case (126):
				return 'applause';
			case (127):
				return 'gun';
		}
	}
};